spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_mc_01
    username: postgres
    password: 2248
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

# Circuit breaker config
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  # Time out issue config for Circuit Breaker
  timelimiter:
    instances:
      inventory:
        timeout-duration:
          seconds: 3
  # Retry time out
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration:
          seconds: 5

# Actuator Config
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


